# Major DRAFT POOL
ALL_PICKS = [
    ('Scott', 'Scottie Scheffler'),
    ('Lucas', 'Rory McIlroy'),
    ('Tom', 'Xander Schauffele'),
    ('David', 'Cameron Young'),
    ('Brady', 'Matt Fitzpatrick'),
    ('Sohale', 'Tommy Fleetwood'),
    ('Jamil', 'Ludvig Åberg'),
    ('Jamil', 'Jon Rahm'),
    ('Sohale', 'Russell Henley'),
    ('Brady', 'Patrick Reed'),
    ('David', 'Bryson DeChambeau'),
    ('Tom', 'Tyrrell Hatton'),
    ('Lucas', 'Chris Gotterup'),
    ('Scott', 'Sam Burns'),
    ('Scott', 'Si Woo Kim'),
    ('Lucas', 'Wyndham Clark'),
    ('Tom', 'Brooks Koepka'),
    ('David', 'Justin Thomas'),
    ('Brady', 'Collin Morikawa'),
    ('Sohale', 'Viktor Hovland'),
    ('Jamil', 'Shane Lowry'),
    ('Jamil', 'Justin Rose'),
    ('Sohale', 'Hideki Matsuyama'),
    ('Brady', 'J.J. Spaun'),
    ('David', 'Patrick Cantlay'),
    ('Tom', 'Robert MacIntyre'),
    ('Lucas', 'Min Woo Lee'),
    ('Scott', 'Aaron Rai'),
    ('Scott', 'Ryan Gerard'),
    ('Lucas', 'Adam Scott'),
    ('Tom', 'Jordan Spieth'),
    ('David', 'Joaquín Niemann'),
    ('Brady', 'Ben Griffin'),
    ('Sohale', 'Sepp Straka'),
    ('Jamil', 'Jason Day'),
    ('Jamil', 'Cameron Smith'),
    ('Sohale', 'Harris English'),
    ('Brady', 'Bud Cauley'),
    ('David', 'Gary Woodland'),
    ('Tom', 'Akshay Bhatia'),
    ('Lucas', 'Kurt Kitayama'),
    ('Scott', 'Alex Fitzpatrick'),
]
