# Major DRAFT POOL
ALL_PICKS = [
    ("Tom ", "Scottie Scheffler"),
    ("Brock", "Cameron Young"),
    ("David", "Rory McIlroy"),
    ("Sohale", "Xander Schauffele"),
    ("Brady", "Ludvig Åberg"),
    ("Lucas", "Jon Rahm"),
    ("Jamil", "Matt Fitzpatrick"),
    ("Jamil", "Bryson DeChambeau"),
    ("Lucas", "Tommy Fleetwood"),
    ("Brady", "Collin Morikawa"),
    ("Sohale", "Nicolai Højgaard"),
    ("David", "Russell Henley"),
    ("Brock", "Brooks Koepka"),
    ("Tom ", "Tyrrell Hatton"),
    ("Tom ", "Shane Lowry"),
    ("Brock", "Sam Burns"),
    ("David", "Patrick Cantlay"),
    ("Sohale", "Chris Gotterup"),
    ("Brady", "Justin Rose"),
    ("Lucas", "Rickie Fowler"),
    ("Jamil", "Jordan Spieth"),
    ("Jamil", "Viktor Hovland"),
    ("Lucas", "J.J. Spaun"),
    ("Brady", "Patrick Reed"),
    ("Sohale", "Justin Thomas"),
    ("David", "Min Woo Lee"),
    ("Brock", "Maverick McNealy"),
    ("Tom ", "Ben Griffin"),
    ("Tom ", "Kristoffer Reitan"),
    ("Brock", "Keegan Bradley"),
    ("David", "Hideki Matsuyama"),
    ("Sohale", "Adam Scott"),
    ("Brady", "Robert MacIntyre"),
    ("Lucas", "Si Woo Kim"),
    ("Jamil", "Akshay Bhatia"),
    ("Jamil", "Gary Woodland"),
    ("Lucas", "Harris English"),
    ("Brady", "Jacob Bridgeman"),
    ("Sohale", "David Puig"),
    ("David", "Sahith Theegala"),
    ("Brock", "Corey Conners"),
    ("Tom ", "Alex Fitzpatrick"),
]
